config/routes.rb
Rails.application.routes.draw do

  get 'pictures/index'

  get 'pictures/show'

  get 'pictures/new'

  get 'pictures/edit'

  get 'completed_hikes/create'

  resources :hikes, only: [:index, :create, :show, :update] do
    resources :reviews, only: [:new, :create, :destroy]
    resources :fave_hikes, only: [:create, :destroy]
    resources :completed_hikes, only: [:create, :destroy]
    collection do
      get :nearby
      get :filter
    end
  end

  resources :users

  resources :pictures


  resource :session, only: [:new, :create, :destroy]

  root to: 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :reviews, dependent: :destroy
  has_many :hikes, through: :fave_hikes
  has_many :hikes, through: :completed_hikes
  has_many :fave_hikes, dependent: :destroy
  has_many :completed_hikes, dependent: :destroy

  has_many :pictures, as: :imageable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password,
    length: { in: 5..20 }, on: :create

  def full_name
    "#{first_name} #{last_name}"
  end

  def kms_hiked
    self.completed_hikes.joins(:hike).references(:hike).sum('hikes.distance_in_km')
  end

  def hiker_level
    dist = self.kms_hiked
    if dist == 0
      "Nature Neophyte"
    elsif dist >= 1 && dist < 20
      "Wayward Wanderer"
    elsif dist >= 20 && dist < 50
      "Tenacious Trekker"
    elsif dist >= 50 && dist < 100
      "Expert Explorer"
    elsif dist >= 100
      "Master Mountaineer"
    end
  end

  def has_not_rated?(hike)
    self.reviews.pluck(:hike_id).exclude?(hike.id)
  end

  def number_of_times_completed(hike)
    self.completed_hikes.pluck(:hike_id).count(hike.id)
  end

  def has_favourited?(hike)
    self.fave_hikes.pluck(:hike_id).include?(hike.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to hikes_path, notice: "Welcome to the trails, #{@user.first_name}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @completed_hikes = @user.completed_hikes
    @fave_hikes = @user.fave_hikes
  end

  protected

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users</h1>

app/views/users/new.html.erb
<div class="container theme-showcase new-user-cont">
  <h3 class ="form-signin-heading">Become a Take a Hike Member</h3>

<!-- Facebook Login -->

<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '1762030974034671',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.5' // use graph api version 2.5
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

<fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button>

<div id="status">
</div>
<br>

<!-- End Facebook Login -->

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= f.text_field :email, placeholder: "Email Address", class: "form-control" %>
    </div>
    <div>
      <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
    </div>
    <div>
      <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
    </div>
    <div>
      <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
    </div>
    <div>
      <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control" %>
    </div>
    <div class="spacer"></div>
    <div><%= f.submit "Submit", class: "btn btn-lg btn-default btn-block new-user" %></div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= title "Profile | Take a hike" %>
<div id="profile-page">

  <section class="hero-profile">

    <div class="container">
      <div id="profile-header" class="row">
        <div id="user-avatar">
          <br>
          <%= link_to image_tag("http://lorempixel.com/60/60/nature/#{@user.id}", width: '60', height: '60', id: '#', alt: 'user avatar') %>
        </div>

        <div id="user-name">
          <h3><%= @user.full_name %></h3>
          <h4>
            <span class="glyphicon glyphicon-signal"></span>
            <%= @user.hiker_level %>
          </h4>
          <h4 id="kms_hiked">
            <span class="glyphicon glyphicon-dashboard"></span>
            <span id="km_text"><%= @user.kms_hiked %> kms</span>
          </h4>
        </div>
      </div> <!-- end of row -->
    </div>

  </section>


  <!-- New Tab Panels -->
  <div class="container">
    <div class="row">
      <div class="col-md-12 folder-tabs">
        <div class="panel with-nav-tabs panel-default">
          <div class="panel-heading">
            <ul class="nav nav-tabs">

              <li class="active">
                <a href="#tab1" data-toggle="tab">
                  <div class="row">

                    <div class="col-xs-12 col-md-2">
                      <h3><span class="glyphicon glyphicon-ok glyph-tab" aria-hidden="true"></span></h3>
                    </div>
                    <div class="main-btn-txt hidden-xs hidden-sm col-md-8">
                      <h4>Completed Hikes</h4>
                    </div>
                  </div>
                </a>
              </li>

              <li>
                <a href="#tab2" data-toggle="tab">
                  <div class="row">
                    <div class="col-xs-12 col-md-2">
                      <h3><span class="glyphicon glyphicon-heart glyph-tab" aria-hidden="true"></span></h3>
                    </div>
                    <div class="main-btn-txt hidden-xs hidden-sm col-md-8">
                      <h4>Favourite Hikes</h4>
                    </div>
                  </div>
                </a>
              </li>

              <li>
                <a href="#tab3" data-toggle="tab">
                  <div class="row">
                    <div class="col-xs-12 col-md-2">
                      <h3><span class="glyphicon glyphicon-pencil glyph-tab" aria-hidden="true"></span></h3>
                    </div>
                    <div class="main-btn-txt hidden-xs hidden-sm col-md-8">
                      <h4>Reviews</h4>
                    </div>
                  </div>
                </a>
              </li>

            </ul>
            </div>
            <div class="panel-body">
              <div class="tab-content">
                <div class="tab-pane fade in active" id="tab1">
                  <table id="completed_hikes_table" class="table table-hover" style="width:100%">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Distance</th>
                        <th class="hide-on-collapse">Difficulty</th>
                        <th class="hide-on-collapse">Date Completed</th>
                        <% if current_user == @user %>
                          <th>Delete</th>
                        <% end %>
                      </tr>
                    </thead>
                    <tbody>
                      <% @completed_hikes.each do |hike| %>
                      <%hike_km = hike.hike.distance_in_km%>
                        <tr>
                          <td><%= link_to hike.hike.name, hike_path(hike.hike_id) %></td>
                          <td><%= hike.hike.distance_in_km %></td>
                          <td class="hide-on-collapse"><%= hike.hike.difficulty %></td>
                          <td class="hide-on-collapse"><%= hike.created_at.strftime("%b %d, %Y") %></td>
                          <% if current_user == @user %>
                            <td>
                            <button class="btn btn-default btn-sm deletable delete-button">Delete</button>
                            <div class="delete-cell">
                              <%= link_to "Yes", hike_completed_hike_path(hike.hike_id, hike.id),
                                    :data => {id: hike_km},
                                    method: :delete,
                                    remote: true,
                                    class: "btn btn-default btn-sm deletable completed_hikes_delete"%>

                              <button class="btn btn-default btn-sm deletable non-delete">No</button>
                            </div>
                          </td>
                          <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <div class="tab-pane fade" id="tab2">
                  <table id="fave_hikes_table" class="table table-hover" style="width:100%">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Distance</th>
                        <th class="hide-on-collapse">Difficulty</th>
                        <% if current_user == @user %>
                          <th>Delete</th>
                        <% end %>
                      </tr>
                    </thead>
                    <tbody>
                      <% @fave_hikes.each do |hike| %>
                        <tr>
                          <td><%= link_to hike.hike.name, hike_path(hike.hike_id) %></td>
                          <td><%= hike.hike.distance_in_km %></td>
                          <td class="hide-on-collapse"><%= hike.hike.difficulty %></td>
                          <% if current_user == @user %>
                            <td>
                            <button class="btn btn-default btn-sm deletable delete-button">Delete</button>
                            <div class="delete-cell">
                              <%= link_to "Yes", hike_fave_hike_path(hike.hike_id, hike.id),
                                    method: :delete,
                                    remote: true,
                                    class: "btn btn-default btn-sm deletable fave_hikes_delete" %>
                              <button class="btn btn-default btn-sm deletable non-delete">No</button>
                            </div>
                          </td>
                          <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <div class="tab-pane fade" id="tab3">
                  <table id="reviews-table" class="table table-hover" style="width:100%">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Review</th>
                        <th class="hide-on-collapse">Rating</th>
                        <% if current_user == @user %>
                          <th>Delete</th>
                        <% end %>
                      </tr>
                    </thead>
                    <tbody>
                      <% @user.reviews.each do |review| %>
                        <tr>
                          <td><%= link_to review.hike.name, hike_path(review.hike_id) %></td>
                          <td><%= review.comment %></td>
                          <td class="hide-on-collapse"><% review.rating.times do %>
                                <span class="rate-tree glyphicon glyphicon-tree-conifer" aria-hidden="true"></span>
                              <% end %>
                          </td>
                          <% if current_user == @user %>
                            <td>
                              <button class="btn btn-default btn-sm deletable delete-button">Delete</button>
                              <div class="delete-cell">
                                <%= link_to "Yes", hike_review_path(review.hike_id, review.id),
                                  method: :delete,
                                  remote: true,
                                  class: "btn btn-default btn-sm deletable reviews_delete" %>
                                <button class="btn btn-default btn-sm deletable non-delete">No</button>
                              </div>
                            </td>
                          <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End of new panel -->

</div>

<%= javascript_include_tag 'jquery.dataTables.min' %>
<%= javascript_include_tag 'user_profile.js' %>