config/routes.rb
Rails.application.routes.draw do

  get 'pictures/index'

  get 'pictures/show'

  get 'pictures/new'

  get 'pictures/edit'

  get 'completed_hikes/create'

  resources :hikes, only: [:index, :create, :show, :update] do
    resources :reviews, only: [:new, :create, :destroy]
    resources :fave_hikes, only: [:create, :destroy]
    resources :completed_hikes, only: [:create, :destroy]
    collection do
      get :nearby
      get :filter
    end
  end

  resources :users

  resources :pictures


  resource :session, only: [:new, :create, :destroy]

  root to: 'welcome#index'

end

app/models/hike.rb
class Hike < ActiveRecord::Base

  has_many :reviews, dependent: :destroy
  has_many :users, through: :fave_hikes
  has_many :users, through: :completed_hikes
  has_many :fave_hikes, dependent: :destroy
  has_many :completed_hikes, dependent: :destroy

  has_many :pictures, as: :imageable
  accepts_nested_attributes_for :images

	validates :name, presence: true
	validates :distance_in_km, numericality: {allow_blank: true, only_integer: true}
	validates :time_in_hours, numericality: {allow_blank: true, only_integer: true}
	validates :difficulty, numericality: {allow_blank: true, only_integer: true}

	serialize :waypoints, Array

  scope :winter, -> { where(winter: true) }
  scope :spring, -> { where(spring: true) }
  scope :summer, -> { where(summer: true) }
  scope :fall, -> { where(fall: true) }
  scope :duration, -> (min, max) { where('time_in_hours >= ? AND time_in_hours <= ?', min, max)}
  scope :difficulty, -> (index) { where('difficulty = ?', index) }
  scope :search_name, -> (search) { where("name iLIKE ?", "%#{search}%") }

  # paginates_per 30

  def difficulty_description
    case self.difficulty
    when 0
      "Easy"
    when 1
      "Medium"
    when 2
      "Hard"
    when 3
      "Extreme"
    end
  end

  def distance_description
    case self.distance_in_km
    when 0
      "Under a km"
    when 1
      "1 km"
    else
      "#{ self.distance_in_km } km"
    end
  end

  def simplified_waypoints(array)
    simplified = []
    array.each_with_index do |point,i|
      simplified << point if i % 2 == 0
    end
    if simplified.length > 300
      return simplified_waypoints(simplified)
    else
      simplified
    end
  end

  def average_rating
    reviews.count > 0 ? (reviews.sum(:rating).to_f/reviews.count).round(0) : 0
  end

  def seasons
    seasons = []
    seasons << "Winter" if winter
    seasons << "Spring" if spring
    seasons << "Summer" if summer
    seasons << "Fall" if fall
    seasons
  end

  def average_rating_sql
    self.reviews.average(:rating)
  end

  def self.top_rated
    review = Review.find_by_sql(
      'SELECT AVG("reviews"."rating") AS average_rating,
        hike_id AS hike_id FROM "reviews"
        GROUP BY "reviews"."hike_id"
        ORDER BY average_rating DESC
        LIMIT 1'
    )
    review.empty? ? Hike.all.sample : review.first.hike
  end

  def self.featured
    Hike.all.sample
  end

end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController

  def index
    @hikes = Hike.select(:id,
      :name,
      :distance_in_km,
      :time_in_hours,
      :difficulty,
    )
    respond_to do |format|
      format.html
      format.json {render json: @hikes}
    end
  end


  def nearby

    bounds = {
      max_lat: params[:position]["max_lat"].to_f,
      min_lat: params[:position]["min_lat"].to_f,
      max_lng: params[:position]["max_lng"].to_f,
      min_lng: params[:position]["min_lng"].to_f
    }

    @hikes = Hike.select('
      "hikes".name, 
      "hikes".id, 
      "hikes".distance_in_km, 
      "hikes".time_in_hours, 
      "hikes".difficulty, 
      "hikes".start_lat, 
      "hikes".start_lng, 
      AVG("reviews".rating) AS avg_rating')
    .joins('LEFT OUTER JOIN reviews ON hikes.id = reviews.hike_id')
    .group(' "hikes".name, "hikes".id')
    .having('start_lat >= ? AND start_lat <= ?', bounds[:min_lat], bounds[:max_lat])
    .having('start_lng >= ? AND start_lng <= ?', bounds[:min_lng], bounds[:max_lng])
    
    @hikes = @hikes.difficulty(params[:difficulty]) if params[:difficulty] && params[:difficulty] != ''

    if params[:duration]
      min,max = params[:duration].split('-')
      @hikes = @hikes.duration(min,max)
    end

    @hikes = @hikes.search_name(params[:name]) if params[:name]

    if current_user
      @hikes_completed = current_user.completed_hikes.pluck(:hike_id)
    else
      @hikes_completed = []
    end

    @response = {
      hikes: @hikes,
      completed: @hikes_completed
    }

    respond_to do |format|
      format.json { render json: @response }
    end
  end

  def show
  	@hike = Hike.find(params[:id])
    @review = Review.new
    @hike_json = @hike.to_json.html_safe
    @hike_waypoints = @hike.simplified_waypoints(@hike.waypoints).to_json.html_safe
    @hike_reviews_json = @hike.reviews.to_json.html_safe
    @average_rating_json = @hike.average_rating.to_json.html_safe
  end

  def edit
  	@hike = Hike.find(params[:id])
  end

  def create
  	@hike = Hike.new(hike_params)

		if @hike.save
		  redirect_to hikes_path
		else
		  render :new
		end
  end

	def destroy
	  @hike = Hike.find(params[:id])
	  @hike.destroy
	  redirect_to hikes_path
	end

  def add_hike
    if current_user
      @hike = Hike.find(params[:id])
      current_user.hikes << @hike
    end
  end

	protected

  def hike_params
    params.require(:hike).permit(
      :name, :distance_in_km, :time_in_hours, :difficulty, :description
    )
  end
end

app/helpers/hikes_helper.rb
module HikesHelper
end

app/views/hikes/_hike.html.erb
<tr class="hike-row" data-name="<%= hike.name %>" >
  <td><%= link_to hike.name, hike_path(hike) %></td>
  <td><%= pluralize(hike.distance_in_km, 'Km') %></td>
  <td><%= pluralize(hike.time_in_hours, 'Hour') %></td>
  <td><%= t('difficulty'+"#{@hike.difficulty}") %></td>
</tr>

app/views/hikes/_pictures.html.erb
<%= form_for @hike, :html => { :class => 'form-horizontal', multipart: true } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <!-- <div class="control-group">
    <%#= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%#= f.text_field :description, :class => 'text_field' %>
    </div>
  </div> -->

  <div class="control-group">
    <%= f.label :pictures, :class => 'control-label' %>
    <div class="controls">
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                hike_path, :class => 'btn btn-mini' %>
  </div>
<% end %>

app/views/hikes/_review.html.erb
<%#= link_to "Rate this hike!", new_hike_review_path(@hike) %>

<% if current_user && current_user.has_not_rated?(@hike) %>
  <div id="new-review-block">
    <h4>Add Your Review of <%= @hike.name %></h4>
    <%= render partial: 'reviews/new' %>
  </div>
<% end %>

<% if @hike.reviews.count > 0 %>
  <button type="button" class="btn btn-default hide-button hike-std-btn" style="display: none;">Hide Reviews </button>
  <button type="button" class="btn btn-default show-button hike-std-btn">Show Reviews </button>  
  <br>
<% end %>

<div id="review-block" class="review-block" style="display: none;">

    <script id="handlebars-review" type="text/x-handlebars-template">​
      <div class="individual-review row">
        <div class="col-xs-3 avatar">
          <img src="http://lorempixel.com/60/60/nature/{{userID}}" class="img-rounded">
          <div class="review-block-name">
            <a href="/users/1">{{username}}</a>
          </div>
        </div>
        

        <div class="col-xs-9">
          <div id="current-user-rating" class="review-block-rate" data-rating={{rating}}>
            <span class="rate-tree glyphicon glyphicon-tree-conifer" aria-hidden="true"></span>
            <span class="rate-tree glyphicon glyphicon-tree-conifer" aria-hidden="true"></span>
            <span class="rate-tree glyphicon glyphicon-tree-conifer" aria-hidden="true"></span>
            <span class="rate-tree glyphicon glyphicon-tree-conifer" aria-hidden="true"></span>
            <span class="rate-tree glyphicon glyphicon-tree-conifer" aria-hidden="true"></span>
          </div>

          <div class="review-block-description">
            <h4>{{comment}}</h4>
          </div>

        </div>
      </div>
    ​</script>
  
  <% @hike.reviews.each do |review| %>
    <div class="individual-review row">     
      <div class="col-xs-3 avatar">
        <img src="http://lorempixel.com/60/60/nature/<%= review.user.id %>" class="img-rounded">
        <div class="review-block-name">
         <%= link_to review.user.full_name, user_path(review.user.id) %>
        </div>
      </div>
      
      <div class="col-xs-9">
        <div class="review-block-rate" data-rating="<%= review.rating %>">
          <!-- RATING FOR EACH REVIEW -->
          <% 5.times do %>
            <span class="rate-tree glyphicon glyphicon-tree-conifer" aria-hidden="true"></span>
          <% end %>
        </div>

        <div class="review-block-description"> 
          <h4><%= review.comment %></h4>
        </div>

      </div>
    </div>
  <% end %>


</div>

<%= javascript_include_tag 'jquery.barrating.min.js' %>
<%= javascript_include_tag 'reviews/reviews.js' %>

app/views/hikes/_search.html.erb
<div class="row search-wrapper">
  <div class="container">

    <h3>Filter Hikes</h3>

    <%= form_tag hikes_path, method: "get", id: "search_form" do %>

      <div class="col-xs-12 col-md-6 form-group">
        <%= text_field_tag :search_name, nil, class: "form-control", placeholder: "Enter hike name here..." %>
      </div>

      <div class="col-xs-12 col-md-3 form-group">
        <%= select_tag(:duration, options_for_select([
          ['Any Duration', '0-24'],
          ['An hour or less', '0-1'],
          ['Less than 5 hours', '2-5'],
          ['More than 5 hours', '6-24']
        ]), class: "form-control") %>
      </div>

      <div class="col-xs-12 col-md-3 form-group">
        <%= select_tag(:difficulty, options_for_select([
          ['Easy', '0'],
          ['Medium', '1'],
          ['Hard', '2'],
          ['Extreme', '3']
        ]), include_blank: "Any Difficulty", class: "form-control" ) %>
      </div>

    <% end %>

  </div>
</div>

app/views/hikes/create.html.erb
<h1>Hikes#create</h1>
<p>Find me in app/views/hikes/create.html.erb</p>

app/views/hikes/edit.html.erb
<h1>Hikes#edit</h1>
<p>Find me in app/views/hikes/edit.html.erb</p>

app/views/hikes/index.html.erb
<%= title "Explore | Take a hike" %>
<%= favicon_link_tag 'mtn.ico' %>
<div class="container-fluid">

	<div class="row">
		<section class="fixed_map">
			<div id="map"></div>
		</section>
	</div>

	<%= render 'search' %>

	<div class="row">
		<div class="container">
			<table id="searched_hikes" class="table table-hover">
				<thead>
					<tr>
						<th>Hike Name</th>
						<th>Distance</th>
						<th>Time</th>
						<th>Difficulty</th>
						<th class="hide-on-collapse">Average Rating</th>
					</tr>
				</thead>
				<tbody>
					<!-- append here with jQuery -->
				</tbody>
			</table>
		</div>
	</div>



</div>
<%= javascript_include_tag 'jquery.dataTables.min' %>
<%= javascript_include_tag 'hikes/hikes_search.js' %>
<%= javascript_include_tag 'hikes/index.js' %>

app/views/hikes/show.html.erb
<%= title "#{@hike.name} | Take a hike" %>
<%= favicon_link_tag 'mtn.ico' %>
<%text = "https://twitter.com/intent/tweet?button_hashtag=TakeAHike&text=I%20just%20finished%20" +@hike.name.gsub(" ","%20") +"!!" %>
<script src="https://www.google.com/jsapi"></script>

<script type="text/javascript">
  var hikeCoordinates = <%=@hike_waypoints%>;
  var reviews = <%=@hike_reviews_json%>;
  var averageRating = <%=@average_rating_json%>;
  var hike = <%=@hike_json%>;
</script>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId=525951207607453";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<div class="container-fluid">
  <div class="hike-header">
    <div class="alert alert-info alert-dismissible flash" style="display: none;">Hike completed!</div>
    <div class="container">
      <div class="col-xs-12">
        <h1 id="hike-title"><%= @hike.name %></h1>
        <div id="times-completed-container">
          <% if current_user && current_user.number_of_times_completed(@hike) >= 1 %>
            <h5 class="times-completed">You have completed this hike <%= pluralize(current_user.number_of_times_completed(@hike), 'time') %></h5>
          <% end %>
        </div>
        <!-- AVERAGE STAR RATING -->
        <% unless @hike.reviews.count == 0 %>
          <div id="rating-block">
            <div class="total-rating" data-rating="<%= @hike.average_rating %>">
              <p>
                <% 5.times do %>
                  <span class="rate-tree glyphicon glyphicon-tree-conifer" aria-hidden="true"></span>
                <% end %>
              </p>
            </div>
          </div>
        <% end %>
        <% if current_user && current_user.has_favourited?(@hike) %>
          <div class="btn btn-default hike-std-btn favourite">
            <i class="glyphicon glyphicon-heart"></i> Marked as Favourite
          </div>
        <% else %>
          <div class="not-favorited">
            <%= link_to hike_fave_hikes_path(params[:id]),
                method: :post,
                remote: true,
                class: "btn btn-default hike-std-btn hike-faved hike-faved" do %>
              <i class="glyphicon glyphicon-heart-empty"></i> Add to Favourites
            <% end %>
          </div>
        <% end %>
        <%= link_to hike_completed_hikes_path(params[:id]),
            method: :post,
            remote: true,
            class: "btn btn-default hike-std-btn hike-complete" do %>
          <i class="glyphicon glyphicon-ok"></i> Mark Completed
        <% end %>
      </div>
    </div>
  </div>

  <div class="container hike-body">
    <!-- HIKE DESCRIPTION SECTION -->
    <div class="col-xs-12 col-md-6 hike_directions" style="display:none">
    <h1> Directions </h1>
    <hr/>
    <div class="hike_steps">
    </div>
    </div>
    <div class="col-xs-12 col-md-6 hide_hike_descriptions">

      <div class="row hike_glyphicon_descriptions">
        <div class="col-xs-12 col-md-6">
          <div class="hike-desc-item">
            <span class="glyphicon glyphicon-record distance-icon" aria-hidden="true"></span>
            <%= pluralize(@hike.distance_in_km, 'Km') %>
          </div>
        </div>
        <div class="col-xs-12 col-md-6">
          <div class="hike-desc-item">
            <span class="glyphicon glyphicon-time time-icon" aria-hidden="true"></span>
            <%= pluralize(@hike.time_in_hours, 'Hour') %>
          </div>
        </div>
        <div class="col-xs-12 col-md-6">
          <div class="hike-desc-item">
            <span class="glyphicon glyphicon-cog difficulty-icon" aria-hidden="true"></span>
            <%= t('difficulty'+"#{@hike.difficulty}") %>
          </div>
        </div>
        <div class="col-xs-12 col-md-6">
          <div class="hike-desc-item">
            <span class="glyphicon glyphicon-leaf seasons-icon" aria-hidden="true"></span>
            <%= @hike.seasons.join(", ") %>
          </div>
        </div>
      </div>

      <div class="row">
          <div class="col-xs-12">
          <h4> Description </h4>
          <p id="hike-description-trunc"><%= truncate(@hike.description, :omission => "...", :length => 300) %></p>
          <% if @hike.description.length >= 300 %>
            <button class="hike-description btn btn-default hike-std-btn" role="button">More</button>
            <button class="hide-hike-description btn btn-default hike-std-btn" style="display: none;" role="button">Less</button>
            <br>
            <br>
          <% end %>
          <% if @hike.description=="" %>
            <p> There is currently no description available. </p>
          <% end %>
        </div>
      </div>

      <hr/>

      <!-- REVIEW SECTION -->
      <div class="row">
        <div class="col-xs-12">
          <%= render partial: 'review' %>
        </div>
      </div>

      <div align="right">
         <a href=<%=text%> class="twitter-hashtag-button">Tweet #TakeAHike</a>
        <div class="fb-send" data-href="http://www.takeahike.co" data-layout="button_count"></div>
        <hr/>

<div class="fb-share-button" data-href="http://takeahike.com" data-layout="button_count" data-mobile-iframe="true"></div>

      </div>

    </div>

    <!-- HIKE MAP AND ELEVATION -->
    <div class="col-xs-12 col-md-6">
        <button class="btn btn-default hike-std-btn" id="directions"> Show Directions </button>
        <button class="btn btn-default hike-std-btn" id="showmap" style="display:none"> Show Hike </button>
        <div class="fixed_map show_map">
        	<div id="map"></div>
        </div>
        <div class="wrapper">
          <div class="fixed_graph">
            <h4> Elevation Change: </h4>
            <div id="elevation_chart"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- NEW WEATHER IFRAME FROM FORECAST.IO -->
<%src="http://forecast.io/embed/#lat="+@hike.start_lat.to_s+"&lon="+@hike.start_lng.to_s+"&name="+@hike.name.gsub(" ","%20")+"&units=ca&color=#484C3B"%>
 <div class="wrapper">
  <div id="weather">
    <iframe id="forecast_embed" type="text/html" frameborder="0" height="245" width="100%" src=<%=src%>>
    </iframe>
  </div>
</div>

<!-- NEW WEATHER IFRAME FROM FORECAST.IO -->

<script>
  google.load('visualization', '1', {packages: ['columnchart']});
</script>


<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

</script>

<%= javascript_include_tag 'hikes/show.js' %>
<%= javascript_include_tag 'hikes/show_ajax.js' %>