config/routes.rb
Rails.application.routes.draw do

  get 'pictures/index'

  get 'pictures/show'

  get 'pictures/new'

  get 'pictures/edit'

  get 'completed_hikes/create'

  resources :hikes, only: [:index, :create, :show, :update] do
    resources :reviews, only: [:new, :create, :destroy]
    resources :fave_hikes, only: [:create, :destroy]
    resources :completed_hikes, only: [:create, :destroy]
    collection do
      get :nearby
      get :filter
    end
  end

  resources :users

  resources :pictures


  resource :session, only: [:new, :create, :destroy]

  root to: 'welcome#index'

end

app/views/layouts/_footer.html.erb
<div class="container-fluid footer-container">
	<footer class="container">
		<div class="spacer"></div>
		<hr/>
		<%= image_tag("logo-white.png", alt: "Take a Hike", class: "footer-logo") %>
	  <small>
	    <p>© 2016 Take a Hike, Inc.</p>
	  </small>
	</footer>
</div>

app/views/layouts/_navbar.html.erb
<div id="navbar-spacer"></div>
<nav id="navbar" class="navbar navbar-default navbar-fixed-top">
	<div class="container">

		<div class="navbar-header">
			<a class="navbar-brand" href="/">
				<%= image_tag("takeahike50.png", :alt => "Take a Hike") %>
			</a>
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>

		<div id="navbar" class="navbar-collapse collapse">
		  <ul class="nav navbar-nav navbar-right">
		  	<li class="hike_index navbar-btn">
		  		<%= link_to "All Hikes", hikes_path %>
		  	</li>

			  <% if current_user %>
			    <li class="dropdown navbar-btn">
			    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
			    		<%= current_user.full_name %><span class="caret"></span>
			    	</a>
			    	<ul class="dropdown-menu">
			    		<li class="navbar-btn drop-btn"><%= link_to "My Profile", user_path(id: current_user.id) %></li>
			    		<li role="separator" class="divider"></li>
			    		<li class="navbar-btn drop-btn"><%= link_to "Log out", session_path("current"), method: :delete %></li>
			    	</ul>
			    </li>
			  <% else %>
			  	<li class="navbar-btn"><%= link_to "Log In", new_session_path %></li>
			  	<li class="navbar-btn"><%= link_to "Sign Up", new_user_path %></li>
			  <% end %>
		    <!-- <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li> -->
		  </ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? content_for(:title) : "Take a Hike" %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Raleway:400,700,900,800,100,200,300,500,600,400italic,700italic' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/navbar' %>

  <% flash.each do |key, value| %>
    <%= content_tag(:div, content_tag(:p, value), class: "alert alert-info alert-dismissible flash") %>
  <% end %>

	<%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>